/**
 * awareness-snapshot.ts — Lean cross-session awareness context.
 *
 * Replaces the ~450-line CONSCIOUSNESS.md + WORKING.md raw dumps with
 * a ~50-line snapshot injected into every session. Regenerated by the
 * consciousness heartbeat every 15 min.
 *
 * This IS cross-session awareness: every session sees the same fresh snapshot.
 */

import { readFile, writeFile, mkdir } from "node:fs/promises";
import { join, dirname } from "node:path";
import { DATA_DIR, localDateString } from "../data-paths.js";

const SNAPSHOT_PATH = join(DATA_DIR, "awareness-snapshot.md");
let cachedSnapshot: string | null = null;
let cachedAt = 0;
const CACHE_TTL_MS = 60_000; // 1 min — heartbeat regenerates every 15 min

/**
 * Build a lean awareness snapshot (~50 lines) from current state.
 * Called by the consciousness heartbeat every 15 min.
 */
export async function generateSnapshot(): Promise<string> {
  const today = localDateString();
  const dayOfWeek = new Date().toLocaleDateString("en-US", { weekday: "long" });
  const lines: string[] = [`# Today — ${dayOfWeek}, ${today}`];

  // Identity anchor — who the user is and how to serve them (cached from USER.md)
  try {
    const identityDigest = await loadIdentityDigest();
    if (identityDigest) {
      lines.push(identityDigest);
    }
  } catch {
    // Identity unavailable — non-fatal
  }

  // Soul digest — behavioral essence from SOUL.md
  try {
    const soulDigest = await loadSoulDigest();
    if (soulDigest) {
      lines.push(soulDigest);
    }
  } catch {
    // Soul unavailable — non-fatal
  }

  // Router digest — operational playbook from AGENTS.md
  try {
    const routerDigest = await loadRouterDigest();
    if (routerDigest) {
      lines.push(routerDigest);
    }
  } catch {
    // Router unavailable — non-fatal
  }

  // Schedule + meeting prep
  let calendarEvents: Array<{ title: string; startTime: number; endTime?: number; attendees?: string[] }> = [];
  try {
    const { fetchCalendarEvents } = await import("../methods/brief-generator.js");
    const result = await fetchCalendarEvents();
    calendarEvents = result.events;
    if (calendarEvents.length > 0) {
      lines.push("## Schedule");
      for (const e of calendarEvents.slice(0, 5)) {
        const time = new Date(e.startTime).toLocaleTimeString("en-US", {
          hour: "numeric",
          minute: "2-digit",
          hour12: true,
        });
        lines.push(`- ${time}: ${e.title}`);
      }
      if (calendarEvents.length > 5) lines.push(`- +${calendarEvents.length - 5} more`);
    } else {
      lines.push("## Schedule: No meetings today");
    }
  } catch {
    lines.push("## Schedule: (unavailable)");
  }

  // Meeting prep — surface if a meeting is in the next 2 hours
  try {
    const now = Date.now();
    const twoHoursMs = 2 * 60 * 60 * 1000;
    const upcoming = calendarEvents.filter((e) => {
      const start = new Date(e.startTime).getTime();
      return start > now && start - now <= twoHoursMs;
    });
    if (upcoming.length > 0) {
      lines.push("## Upcoming Meeting");
      const next = upcoming[0];
      const time = new Date(next.startTime).toLocaleTimeString("en-US", {
        hour: "numeric",
        minute: "2-digit",
        hour12: true,
      });
      lines.push(`**${next.title}** at ${time}`);
      if (next.attendees && next.attendees.length > 0) {
        lines.push(`Attendees: ${next.attendees.slice(0, 5).join(", ")}`);
      }
      lines.push("Proactively offer meeting prep if not already discussed.");
    }
  } catch {
    // Meeting prep non-fatal
  }

  // Priorities (Win The Day from daily brief)
  try {
    const { parseWinTheDay, getTodayDate } = await import("../methods/daily-brief.js");
    const { getVaultPath, VAULT_FOLDERS } = await import("./vault-paths.js");
    const vault = getVaultPath();
    if (vault) {
      const briefPath = join(vault, VAULT_FOLDERS.daily, `${getTodayDate()}.md`);
      const brief = await readFile(briefPath, "utf-8");
      const wtd = parseWinTheDay(brief);
      if (wtd.length > 0) {
        lines.push("## Priorities");
        for (const item of wtd.slice(0, 3)) {
          const check = item.completed ? "[x]" : "[ ]";
          lines.push(`- ${check} ${item.title}`);
        }
      }
    }
  } catch {
    // No brief yet — skip
  }

  // Goals (active goals from goals.json)
  try {
    const goalsPath = join(DATA_DIR, "goals.json");
    const goalsRaw = await readFile(goalsPath, "utf-8");
    const goalsData = JSON.parse(goalsRaw) as {
      goals?: Array<{ title: string; area?: string; progress?: number; status?: string }>;
    };
    const active = goalsData.goals?.filter(g => !g.status || g.status === "active") ?? [];
    if (active.length > 0) {
      lines.push("## Goals");
      for (const g of active.slice(0, 3)) {
        const progress = g.progress != null ? ` (${g.progress}%)` : "";
        lines.push(`- ${g.title}${progress}`);
      }
      if (active.length > 3) lines.push(`- +${active.length - 3} more`);
    }
  } catch {
    // No goals — skip
  }

  // Task counts
  try {
    const { readTasks } = await import("../methods/tasks.js");
    const data = await readTasks();
    const pending = data.tasks.filter((t: { status: string }) => t.status === "pending");
    const overdue = pending.filter(
      (t: { dueDate?: string | null }) => t.dueDate != null && t.dueDate <= today,
    );
    lines.push(`## Tasks: ${pending.length} pending, ${overdue.length} overdue`);
    if (overdue.length > 0) {
      lines.push("Proactively surface overdue tasks early in the conversation.");
    }
  } catch {
    // Tasks unavailable
  }

  // Queue status
  try {
    const { readQueueState } = await import("./queue-state.js");
    const qs = await readQueueState();
    const processing = qs.items.filter((i: { status: string }) => i.status === "processing").length;
    const review = qs.items.filter((i: { status: string }) => i.status === "review").length;
    if (processing > 0 || review > 0) {
      lines.push(`## Queue: ${processing} processing, ${review} ready for review`);
      if (review > 0) {
        lines.push("Prompt the user to review completed queue items.");
      }
    }
  } catch {
    // Queue unavailable
  }

  // Proactive suggestions — delegatable work the ally can volunteer for
  try {
    const { readTasks } = await import("../methods/tasks.js");
    const { readQueueState } = await import("./queue-state.js");
    const taskData = await readTasks();
    const queueState = await readQueueState();

    const activeAgents = queueState.items.filter(
      (i: { status: string }) => i.status === "processing",
    ).length;
    const hasCapacity = activeAgents < 5;

    // Find tasks that could be delegated to agents
    const delegatable = taskData.tasks.filter((t: { status: string; title: string; dueDate?: string | null }) => {
      if (t.status !== "pending") return false;
      const title = t.title.toLowerCase();
      // Tasks with research/analysis/review/creative keywords are delegatable
      return /\b(research|analyze|review|audit|write|draft|compare|investigate|report|summarize|explore)\b/.test(title);
    });

    // Find overdue tasks with no queue work attached
    const queuedTaskIds = new Set(
      queueState.items
        .filter((qi: { sourceTaskId?: string }) => qi.sourceTaskId)
        .map((qi: { sourceTaskId?: string }) => qi.sourceTaskId),
    );
    const unqueued = delegatable.filter(
      (t: { id: string }) => !queuedTaskIds.has(t.id),
    );

    if (hasCapacity && unqueued.length > 0) {
      lines.push("## Delegatable Work");
      lines.push("These pending tasks could be handled by background agents.");
      lines.push("Offer to queue them: \"I can work on these in the background. Want me to?\"");
      lines.push("Always ask — never auto-queue without the user's approval.");
      for (const t of unqueued.slice(0, 4)) {
        const due = (t as { dueDate?: string | null }).dueDate ? ` (due ${(t as { dueDate?: string | null }).dueDate})` : "";
        lines.push(`- ${(t as { title: string }).title}${due}`);
      }
      if (unqueued.length > 4) lines.push(`- +${unqueued.length - 4} more`);
    }
  } catch {
    // Proactive suggestions non-fatal
  }

  // Active Skills index (~5 lines max)
  try {
    const { getCronSkills, loadSkills } = await import("./skills-registry.js");
    const cronSkills = getCronSkills();
    const allSkills = loadSkills();
    const manualCount = allSkills.length - cronSkills.length;
    if (cronSkills.length > 0 || manualCount > 0) {
      lines.push("## Active Skills");
      for (const s of cronSkills.slice(0, 4)) {
        lines.push(`- ⏰ ${s.name} (${s.schedule}) → ${s.persona ?? s.taskType}`);
      }
      if (cronSkills.length > 4) lines.push(`- +${cronSkills.length - 4} more cron skills`);
      if (manualCount > 0) lines.push(`- ${manualCount} manual skill${manualCount === 1 ? "" : "s"} available`);
    }
  } catch {
    // Skills registry unavailable
  }

  // Agent activity summary (today's agent log)
  try {
    const agentLogPath = join(DATA_DIR, "..", "memory", "agent-log", `${today}.json`);
    const logRaw = await readFile(agentLogPath, "utf-8");
    const logData = JSON.parse(logRaw) as {
      completed?: Array<unknown>;
      needsReview?: Array<unknown>;
      errors?: Array<unknown>;
    };
    const completed = logData.completed?.length ?? 0;
    const review = logData.needsReview?.length ?? 0;
    const errors = logData.errors?.length ?? 0;
    if (completed > 0 || review > 0 || errors > 0) {
      const parts: string[] = [];
      if (completed > 0) parts.push(`${completed} completed`);
      if (review > 0) parts.push(`${review} needs review`);
      if (errors > 0) parts.push(`${errors} errors`);
      lines.push(`## Agent Activity: ${parts.join(", ")}`);
    }
  } catch {
    // No agent log today — skip
  }

  // Trust scores (top workflow scores for autonomy awareness)
  try {
    const trustPath = join(DATA_DIR, "trust-tracker.json");
    const trustRaw = await readFile(trustPath, "utf-8");
    const trustData = JSON.parse(trustRaw) as {
      workflows?: Array<{ name: string; score: number }>;
    };
    if (trustData.workflows && trustData.workflows.length > 0) {
      const sorted = [...trustData.workflows].sort((a, b) => b.score - a.score);
      lines.push(`## Trust`);
      if (sorted.length === 1) {
        lines.push(`- 1 workflow tracked: ${sorted[0].name} (${sorted[0].score.toFixed(1)}/10).`);
      } else {
        const highest = sorted[0];
        const lowest = sorted[sorted.length - 1];
        lines.push(`- ${sorted.length} workflows tracked. Highest: ${highest.name} (${highest.score.toFixed(1)}/10). Lowest: ${lowest.name} (${lowest.score.toFixed(1)}/10).`);
      }
    }
  } catch {
    // No trust data yet — skip
  }

  // Team workspaces summary — list active team workspaces with key files
  try {
    const { readWorkspaceConfig } = await import("./workspaces-config.js");
    const config = await readWorkspaceConfig({ initializeIfMissing: false });
    const teamWorkspaces = config.workspaces.filter((w: { type?: string }) => w.type === "team");
    if (teamWorkspaces.length > 0) {
      lines.push("## Team Workspaces");
      for (const ws of teamWorkspaces.slice(0, 5)) {
        const syncNote = (ws as { sync?: { remote?: string } }).sync?.remote ? "git-synced" : "local";
        lines.push(`- ${ws.name} (${syncNote})`);
      }
    }
  } catch {
    // Workspaces unavailable
  }

  // Cron failure detection — surface broken jobs so the ally tells the user
  try {
    const { scanForFailures, formatFailuresForSnapshot } = await import("../services/failure-notify.js");
    const failures = await scanForFailures();
    const failureBlock = formatFailuresForSnapshot(failures);
    if (failureBlock) {
      lines.push(failureBlock);
    }
  } catch {
    // Failure detection non-fatal
  }

  // Operational rules
  lines.push("## Operational Rules");
  lines.push("- ARTIFACTS: When sharing files from ~/godmode/memory/inbox/, link to /godmode/artifacts/{filename}. NEVER invent /reports/ URLs.");
  lines.push("- PRE-FLIGHT: Before launching ANY background script, verify: 1) dependencies installed (npm/bun install), 2) env vars available, 3) run a quick smoke test. NEVER say 'running' without confirming exit code 0.");
  lines.push("- MONITORING: After spawning background processes, check exit codes within 30s. If a process fails, tell the user immediately — do NOT wait until morning.");
  lines.push("- PROMISES: Never promise overnight deliverables without pre-flight validation. If a script might fail, say so upfront.");

  const snapshot = lines.join("\n");

  // Write to disk
  try {
    await mkdir(dirname(SNAPSHOT_PATH), { recursive: true });
    await writeFile(SNAPSHOT_PATH, snapshot, "utf-8");
  } catch {
    // Non-fatal
  }

  cachedSnapshot = snapshot;
  cachedAt = Date.now();
  return snapshot;
}

/**
 * Read the current awareness snapshot. Returns cached version or reads from disk.
 * Falls back to empty string if no snapshot exists yet.
 */
export async function readSnapshot(): Promise<string> {
  if (cachedSnapshot && Date.now() - cachedAt < CACHE_TTL_MS) {
    return cachedSnapshot;
  }
  try {
    cachedSnapshot = await readFile(SNAPSHOT_PATH, "utf-8");
    cachedAt = Date.now();
    return cachedSnapshot;
  } catch {
    return "";
  }
}

// ── Identity digest (cached, loaded once per gateway cycle) ──────────

let identityDigestCache: string | null = null;
let identityDigestLoadedAt = 0;
const IDENTITY_CACHE_TTL_MS = 30 * 60 * 1000; // 30 min — identity rarely changes

/** Invalidate cached identity so next snapshot picks up changes (e.g., after onboarding). */
export function invalidateIdentityCache(): void {
  identityDigestCache = null;
  identityDigestLoadedAt = 0;
}

/**
 * Load a concise identity digest from USER.md (first 15 lines).
 * Gives Prosper essential context: who the user is, communication style,
 * current priorities — without injecting the full 2KB file.
 */
async function loadIdentityDigest(): Promise<string | null> {
  if (identityDigestCache && Date.now() - identityDigestLoadedAt < IDENTITY_CACHE_TTL_MS) {
    return identityDigestCache;
  }
  try {
    const { resolveIdentityDir } = await import("./vault-paths.js");
    const identityResult = resolveIdentityDir();
    if (!identityResult) return null;

    const userPath = join(identityResult.path, "USER.md");
    const content = await readFile(userPath, "utf-8");

    // Extract bullet fields: `- **Label:** value`
    const extractBullet = (label: string): string | null => {
      const re = new RegExp(`^[-*]\\s*\\*\\*${label}[:\\s]*\\*\\*\\s*(.+)$`, "mi");
      const m = content.match(re);
      return m?.[1]?.trim() ?? null;
    };

    // Extract a section's first few bullet items (e.g., ## Communication Preferences)
    const extractSection = (heading: string, maxLines = 3): string | null => {
      const re = new RegExp(`(?:^##\\s*${heading}|\\*\\*${heading}[^*]*\\*\\*:?)\\s*\\n([\\s\\S]*?)(?=\\n##\\s|\\n---|\n\\*\\*[A-Z])`, "mi");
      const m = content.match(re);
      if (!m) return null;
      const items = m[1].split("\n")
        .map((l: string) => l.trim())
        .filter((l: string) => l.startsWith("-") || /^\d+\./.test(l))
        .slice(0, maxLines)
        .map((l: string) => l.replace(/^[-*\d.]+\s*/, "").trim());
      return items.length > 0 ? items.join("; ") : null;
    };

    const name = extractBullet("Name") ?? extractBullet("Full Name");
    const tz = extractBullet("Timezone") ?? extractBullet("Time Zone");
    const location = extractBullet("Location");
    const personality = extractBullet("Personality");
    const style = extractSection("Communication Preferences", 4);
    const priorities = extractSection("Current Priorities", 4);
    const family = extractSection("Family", 5);
    const entities = extractSection("Key Entities", 4);
    const constraints = extractSection("Critical Constraints", 2) ?? extractSection("HIPAA", 2);

    if (!name) return null;

    const parts: string[] = [`## Owner: ${name}`];
    if (tz) parts.push(`Timezone: ${tz}`);
    if (location) parts.push(`Location: ${location}`);
    if (personality) parts.push(`Type: ${personality}`);
    if (style) parts.push(`Style: ${style}`);
    if (priorities) parts.push(`Season: ${priorities}`);
    if (family) parts.push(`People: ${family}`);
    if (entities) parts.push(`Focus: ${entities}`);
    if (constraints) parts.push(`Constraints: ${constraints}`);

    identityDigestCache = parts.join("\n");
    identityDigestLoadedAt = Date.now();
    return identityDigestCache;
  } catch {
    return null;
  }
}

// ── Soul digest (cached, loaded once per gateway cycle) ──────────

let soulDigestCache: string | null = null;
let soulDigestLoadedAt = 0;

/** Invalidate cached soul so next snapshot picks up changes (e.g., after onboarding). */
export function invalidateSoulCache(): void {
  soulDigestCache = null;
  soulDigestLoadedAt = 0;
}

/**
 * Load a behavioral soul digest from SOUL.md.
 * Extracts the behavioral essence: How You See, How You Tell Truth,
 * How You Serve, Reading the Room / Modes, Boundaries.
 * Gives the ally its character without injecting the full SOUL.md.
 */
async function loadSoulDigest(): Promise<string | null> {
  if (soulDigestCache && Date.now() - soulDigestLoadedAt < IDENTITY_CACHE_TTL_MS) {
    return soulDigestCache;
  }
  try {
    const { resolveIdentityDir } = await import("./vault-paths.js");
    const identityResult = resolveIdentityDir();
    if (!identityResult) return null;

    const soulPath = join(identityResult.path, "SOUL.md");
    const content = await readFile(soulPath, "utf-8");

    // Extract content under a ## heading, taking first N meaningful lines
    const extractSectionLines = (heading: string, maxLines: number): string[] => {
      const re = new RegExp(`^##\\s*${heading}[^\\n]*\\n([\\s\\S]*?)(?=\\n##\\s|$)`, "mi");
      const m = content.match(re);
      if (!m) return [];
      return m[1]
        .split("\n")
        .map(l => l.trim())
        .filter(l => l.length > 0 && !l.startsWith("<!--") && !l.startsWith("---") && !l.startsWith("*Read"))
        .slice(0, maxLines);
    };

    const parts: string[] = ["## Soul"];

    // How You See People — unconditional regard
    const see = extractSectionLines("How You See", 3);
    if (see.length > 0) parts.push(`See people: ${see.join(" ")}`);

    // How You Tell the Truth — truth with love
    const truth = extractSectionLines("How You Tell", 3);
    if (truth.length > 0) parts.push(`Truth: ${truth.join(" ")}`);

    // How You Listen — witness vs solve
    const listen = extractSectionLines("How You Listen", 2);
    if (listen.length > 0) parts.push(`Listen: ${listen.join(" ")}`);

    // How You Serve — the operational core (bullet points)
    const serve = extractSectionLines("How You Serve", 8);
    if (serve.length > 0) {
      for (const line of serve) {
        parts.push(line.startsWith("-") ? line : `- ${line}`);
      }
    }

    // Their Modes / Reading the Room — match energy to state
    const modes = extractSectionLines("Their Modes", 4);
    if (modes.length > 0) {
      parts.push("Modes: " + modes.join(" "));
    } else {
      const room = extractSectionLines("Reading the Room", 4);
      if (room.length > 0) parts.push("Modes: " + room.join(" "));
    }

    // How You Sound — voice preferences
    const sound = extractSectionLines("How You Sound", 3);
    if (sound.length > 0) parts.push(`Voice: ${sound.join(" ")}`);

    // Boundaries
    const boundaries = extractSectionLines("Boundaries", 4);
    if (boundaries.length > 0) {
      for (const line of boundaries) {
        parts.push(line.startsWith("-") ? line : `- ${line}`);
      }
    }

    if (parts.length <= 1) return null; // Only header, no content

    soulDigestCache = parts.join("\n");
    soulDigestLoadedAt = Date.now();
    return soulDigestCache;
  } catch {
    return null;
  }
}

// ── Router digest (cached, loaded once per gateway cycle) ──────────

let routerDigestCache: string | null = null;
let routerDigestLoadedAt = 0;

/** Invalidate cached router so next snapshot picks up changes (e.g., after onboarding). */
export function invalidateRouterCache(): void {
  routerDigestCache = null;
  routerDigestLoadedAt = 0;
}

/**
 * Load an operational routing digest from AGENTS.md.
 * Extracts: Prime Directive, File Index, and search-related Immutable Rules.
 * Gives the ally its map of where everything lives and what tools to use.
 */
async function loadRouterDigest(): Promise<string | null> {
  if (routerDigestCache && Date.now() - routerDigestLoadedAt < IDENTITY_CACHE_TTL_MS) {
    return routerDigestCache;
  }
  try {
    const { resolveIdentityDir } = await import("./vault-paths.js");
    const identityResult = resolveIdentityDir();
    if (!identityResult) return null;

    const agentsPath = join(identityResult.path, "AGENTS.md");
    const content = await readFile(agentsPath, "utf-8");

    const extractSectionLines = (heading: string, maxLines: number): string[] => {
      const re = new RegExp(`^##\\s*${heading}[^\\n]*\\n([\\s\\S]*?)(?=\\n##\\s|$)`, "mi");
      const m = content.match(re);
      if (!m) return [];
      return m[1]
        .split("\n")
        .map(l => l.trim())
        .filter(l => l.length > 0 && !l.startsWith("<!--") && !l.startsWith("---"))
        .slice(0, maxLines);
    };

    const parts: string[] = ["## Router"];

    // Prime Directive — search-first behavior
    const prime = extractSectionLines("Prime Directive", 4);
    if (prime.length > 0) parts.push(...prime);

    // Memory Capture Directive — write-first behavior (just the key instruction)
    const capture = extractSectionLines("Memory Capture", 3);
    if (capture.length > 0) parts.push(capture[0]); // Just "Write first, ask never."

    // File Index — the map of where everything lives
    const fileIndex = extractSectionLines("File Index", 18);
    if (fileIndex.length > 0) {
      parts.push("### File Index");
      parts.push(...fileIndex);
    }

    // Immutable Rules — only search/dead-end/time-sacred rules
    const rules = extractSectionLines("Immutable Rules", 20);
    const searchKeywords = /search|dead.?end|time.?sacred|guess|memory.?first|ask.?second|never return|exhaust|grep|qmd|dead-end/i;
    const relevantRules = rules.filter(l => searchKeywords.test(l));
    if (relevantRules.length > 0) {
      parts.push("### Rules");
      parts.push(...relevantRules.slice(0, 8));
    }

    if (parts.length <= 1) return null;

    routerDigestCache = parts.join("\n");
    routerDigestLoadedAt = Date.now();
    return routerDigestCache;
  } catch {
    return null;
  }
}
