/**
 * awareness-snapshot.ts — Lean cross-session awareness context.
 *
 * Replaces the ~450-line CONSCIOUSNESS.md + WORKING.md raw dumps with
 * a ~50-line snapshot injected into every session. Regenerated by the
 * consciousness heartbeat every 15 min.
 *
 * This IS cross-session awareness: every session sees the same fresh snapshot.
 */

import { readFile, writeFile, mkdir } from "node:fs/promises";
import { join, dirname } from "node:path";
import { DATA_DIR, localDateString } from "../data-paths.js";

const SNAPSHOT_PATH = join(DATA_DIR, "awareness-snapshot.md");
let cachedSnapshot: string | null = null;
let cachedAt = 0;
const CACHE_TTL_MS = 60_000; // 1 min — heartbeat regenerates every 15 min

/**
 * Build a lean awareness snapshot (~50 lines) from current state.
 * Called by the consciousness heartbeat every 15 min.
 */
export async function generateSnapshot(): Promise<string> {
  const today = localDateString();
  const lines: string[] = [`# Today — ${today}`];

  // Identity anchor — who the user is and how to serve them (cached from USER.md)
  try {
    const identityDigest = await loadIdentityDigest();
    if (identityDigest) {
      lines.push(identityDigest);
    }
  } catch {
    // Identity unavailable — non-fatal
  }

  // Schedule + meeting prep
  let calendarEvents: Array<{ title: string; startTime: number; endTime?: number; attendees?: string[] }> = [];
  try {
    const { fetchCalendarEvents } = await import("../methods/brief-generator.js");
    const result = await fetchCalendarEvents();
    calendarEvents = result.events;
    if (calendarEvents.length > 0) {
      lines.push("## Schedule");
      for (const e of calendarEvents.slice(0, 5)) {
        const time = new Date(e.startTime).toLocaleTimeString("en-US", {
          hour: "numeric",
          minute: "2-digit",
          hour12: true,
        });
        lines.push(`- ${time}: ${e.title}`);
      }
      if (calendarEvents.length > 5) lines.push(`- +${calendarEvents.length - 5} more`);
    } else {
      lines.push("## Schedule: No meetings today");
    }
  } catch {
    lines.push("## Schedule: (unavailable)");
  }

  // Meeting prep — surface if a meeting is in the next 2 hours
  try {
    const now = Date.now();
    const twoHoursMs = 2 * 60 * 60 * 1000;
    const upcoming = calendarEvents.filter((e) => {
      const start = new Date(e.startTime).getTime();
      return start > now && start - now <= twoHoursMs;
    });
    if (upcoming.length > 0) {
      lines.push("## Upcoming Meeting");
      const next = upcoming[0];
      const time = new Date(next.startTime).toLocaleTimeString("en-US", {
        hour: "numeric",
        minute: "2-digit",
        hour12: true,
      });
      lines.push(`**${next.title}** at ${time}`);
      if (next.attendees && next.attendees.length > 0) {
        lines.push(`Attendees: ${next.attendees.slice(0, 5).join(", ")}`);
      }
      lines.push("Proactively offer meeting prep if not already discussed.");
    }
  } catch {
    // Meeting prep non-fatal
  }

  // Priorities (Win The Day from daily brief)
  try {
    const { parseWinTheDay, getTodayDate } = await import("../methods/daily-brief.js");
    const { getVaultPath, VAULT_FOLDERS } = await import("./vault-paths.js");
    const vault = getVaultPath();
    if (vault) {
      const briefPath = join(vault, VAULT_FOLDERS.daily, `${getTodayDate()}.md`);
      const brief = await readFile(briefPath, "utf-8");
      const wtd = parseWinTheDay(brief);
      if (wtd.length > 0) {
        lines.push("## Priorities");
        for (const item of wtd.slice(0, 3)) {
          const check = item.completed ? "[x]" : "[ ]";
          lines.push(`- ${check} ${item.title}`);
        }
      }
    }
  } catch {
    // No brief yet — skip
  }

  // Task counts
  try {
    const { readTasks } = await import("../methods/tasks.js");
    const data = await readTasks();
    const pending = data.tasks.filter((t: { status: string }) => t.status === "pending");
    const overdue = pending.filter(
      (t: { dueDate?: string | null }) => t.dueDate != null && t.dueDate <= today,
    );
    lines.push(`## Tasks: ${pending.length} pending, ${overdue.length} overdue`);
  } catch {
    // Tasks unavailable
  }

  // Queue status
  try {
    const { readQueueState } = await import("./queue-state.js");
    const qs = await readQueueState();
    const processing = qs.items.filter((i: { status: string }) => i.status === "processing").length;
    const review = qs.items.filter((i: { status: string }) => i.status === "review").length;
    if (processing > 0 || review > 0) {
      lines.push(`## Queue: ${processing} processing, ${review} ready for review`);
    }
  } catch {
    // Queue unavailable
  }

  const snapshot = lines.join("\n");

  // Write to disk
  try {
    await mkdir(dirname(SNAPSHOT_PATH), { recursive: true });
    await writeFile(SNAPSHOT_PATH, snapshot, "utf-8");
  } catch {
    // Non-fatal
  }

  cachedSnapshot = snapshot;
  cachedAt = Date.now();
  return snapshot;
}

/**
 * Read the current awareness snapshot. Returns cached version or reads from disk.
 * Falls back to empty string if no snapshot exists yet.
 */
export async function readSnapshot(): Promise<string> {
  if (cachedSnapshot && Date.now() - cachedAt < CACHE_TTL_MS) {
    return cachedSnapshot;
  }
  try {
    cachedSnapshot = await readFile(SNAPSHOT_PATH, "utf-8");
    cachedAt = Date.now();
    return cachedSnapshot;
  } catch {
    return "";
  }
}

// ── Identity digest (cached, loaded once per gateway cycle) ──────────

let identityDigestCache: string | null = null;
let identityDigestLoadedAt = 0;
const IDENTITY_CACHE_TTL_MS = 30 * 60 * 1000; // 30 min — identity rarely changes

/**
 * Load a concise identity digest from USER.md (first 15 lines).
 * Gives Prosper essential context: who the user is, communication style,
 * current priorities — without injecting the full 2KB file.
 */
async function loadIdentityDigest(): Promise<string | null> {
  if (identityDigestCache && Date.now() - identityDigestLoadedAt < IDENTITY_CACHE_TTL_MS) {
    return identityDigestCache;
  }
  try {
    const { resolveIdentityDir } = await import("./vault-paths.js");
    const identityResult = resolveIdentityDir();
    if (!identityResult) return null;

    const userPath = join(identityResult.path, "USER.md");
    const content = await readFile(userPath, "utf-8");

    // Extract bullet fields: `- **Label:** value`
    const extractBullet = (label: string): string | null => {
      const re = new RegExp(`^[-*]\\s*\\*\\*${label}[:\\s]*\\*\\*\\s*(.+)$`, "mi");
      const m = content.match(re);
      return m?.[1]?.trim() ?? null;
    };

    // Extract a section's first few bullet items (e.g., ## Communication Preferences)
    const extractSection = (heading: string, maxLines = 3): string | null => {
      const re = new RegExp(`(?:^##\\s*${heading}|\\*\\*${heading}[^*]*\\*\\*:?)\\s*\\n([\\s\\S]*?)(?=\\n##\\s|\\n---|\n\\*\\*[A-Z])`, "mi");
      const m = content.match(re);
      if (!m) return null;
      const items = m[1].split("\n")
        .map((l: string) => l.trim())
        .filter((l: string) => l.startsWith("-") || /^\d+\./.test(l))
        .slice(0, maxLines)
        .map((l: string) => l.replace(/^[-*\d.]+\s*/, "").trim());
      return items.length > 0 ? items.join("; ") : null;
    };

    const name = extractBullet("Name") ?? extractBullet("Full Name");
    const tz = extractBullet("Timezone") ?? extractBullet("Time Zone");
    const style = extractSection("Communication Preferences", 3);
    const priorities = extractSection("Current Priorities", 4);

    if (!name) return null;

    const parts: string[] = [`## Owner: ${name}`];
    if (tz) parts.push(`Timezone: ${tz}`);
    if (style) parts.push(`Style: ${style}`);
    if (priorities) parts.push(`Season: ${priorities}`);

    identityDigestCache = parts.join("\n");
    identityDigestLoadedAt = Date.now();
    return identityDigestCache;
  } catch {
    return null;
  }
}
