#!/bin/bash
# godmode-wip-commit.sh - Auto-commit WIP to prevent work loss
#
# Call this:
#   - Before any upstream sync
#   - At the end of any AI tool session
#   - Before switching between AI tools (Codex, Claude, GPT, etc.)
#
# Safe to call repeatedly. Does nothing if there are no changes.

set -e

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

TIMESTAMP=$(date +%Y%m%d-%H%M%S)

# Check if there are any changes to commit
if git diff --quiet HEAD && git diff --cached --quiet && [ -z "$(git ls-files --others --exclude-standard)" ]; then
    echo "[WIP] No uncommitted changes. Nothing to do."
    exit 0
fi

# Count changes
MODIFIED=$(git diff --name-only HEAD | wc -l | tr -d ' ')
STAGED=$(git diff --cached --name-only | wc -l | tr -d ' ')
UNTRACKED=$(git ls-files --others --exclude-standard | wc -l | tr -d ' ')
TOTAL=$((MODIFIED + STAGED + UNTRACKED))

echo "[WIP] Found ${TOTAL} changed files (${MODIFIED} modified, ${STAGED} staged, ${UNTRACKED} new)"

# Stage everything
git add -A

# Build a short summary of what's changing
SUMMARY=$(git diff --cached --stat | tail -1)

# Commit with --no-verify (WIP commits skip lint to avoid blocking safety checkpoints)
git commit --no-verify -m "WIP: auto-checkpoint ${TIMESTAMP}

${TOTAL} files: ${SUMMARY}

Auto-generated by godmode-wip-commit.sh to prevent work loss.
Call 'git log --oneline -5' to see recent checkpoints."

COMMIT_HASH=$(git rev-parse --short HEAD)
echo "[WIP] Committed as ${COMMIT_HASH}: ${TOTAL} files checkpointed"
echo "[WIP] To undo: git reset --soft HEAD~1"
